lib/example_oauth_web/router.ex
defmodule ExampleOauthWeb.Router do
  use ExampleOauthWeb, :router

  # before we want to do some preprocessing before
  # any request hits a route
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ExampleOauthWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExampleOauthWeb do
    pipe_through :browser

    # get "/", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update

    resources "/", TopicController
  end

  scope "/auth", ExampleOauthWeb do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExampleOauthWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ExampleOauthWeb.Telemetry
    end
  end
end

lib/example_oauth_web/views/layout_view.ex
defmodule ExampleOauthWeb.LayoutView do
  use ExampleOauthWeb, :view
end

lib/example_oauth_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ExampleOauth</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = `<%= Phoenix.Token.sign(
          ExampleOauthWeb.Endpoint,
          "key",
          @conn.assigns.user.id
         ) %>`
      <% end %>
    </script>
  </head>
  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href ="/">
          <img style="max-height:100%; padding: 0.8em"
               src="<%= Routes.static_path(@conn, "/images/logo.png") %>">
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
            <%= link "Sign Out", to: Routes.auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Discord",
                  to: Routes.auth_path(@conn, :request, "discord") %>
            </li>
          <% end %>
          <li>
            <a class="dark-toggle" href="#">
              <i class="material-icons left">brightness_4</i>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </div>
  </body>
</html>